# Generated by Django 3.0.6 on 2020-09-18 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('projector', models.BooleanField(default=False)),
            ],
        ),
    ]
