# Generated by Django 3.0.6 on 2020-09-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_workshop', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
